### ISSUE TITLE
2-Mockup Login

### ISSUE THREAD

**Issue by Migueleando** [Migueleando/Tallerizat#2]
Una vez que clicas en Mecanico, como sabemos en que puesto esta situadoo?

**Comment by Migueleando** [comment]
Dos opciones:
Mecánico
Administración
Al elegir mecánico pedirá el nombre para añadirlo a la lista de mecánicos o que seleccione uno de la lista, en caso de escribir nombre y seleccionar uno de la lista saltara un warning que no le dejara avanzar a no ser que seleccione una de las dos opciones(sleccionar o anadir)

**Comment by chufaschufurius** [comment]
OK
