### ISSUE TITLE
4-Mockup Datos cliente

### ISSUE THREAD

**Issue by Migueleando** [Migueleando/Tallerizat#3]

**Comment by Migueleando** [comment]
-Se introducen los datos básicos del cliente.
Nombre, teléfono, email, matrícula y tareas a realizar al vehículo.

**Comment by Migueleando** [comment]
-Se introducen los datos básicos del cliente.
Nombre, teléfono, email, matrícula y tareas a realizar al vehículo.

**Comment by chufaschufurius** [comment]
OK
