### ISSUE TITLE
8-Mockup tipo de averia

### ISSUE THREAD

**Issue by Migueleando** [Migueleando/Tallerizat#5]

**Comment by Migueleando** [comment]
El icono seleccionado anteriormente en la parte superior.
Datos:
modelo, año, matrícula y tipo de motor.
Trabajo a realizar:
Aparecerán dos tareas muy comunes  y "Otros", que se podrán seleccionar con un check.
-Revisión (al lado tendremos que introducir cuantos kilómetros tiene al coche)
-Cambio de neumáticos (al lado tendremos que introducir la medida)
-Otros (en caso de seleccionar esta opción aparecerá un área para introducir texto libremente donde describiremos lo que el cliente nos indique.
Podremos seleccionar una o varias opciones, si no se selecciona ninguna o falta algún datos por introducir, mostraremos mensaje de error (faltan datos).
Dos botones en la parte inferior:
-Atrás
-Guardar

###########################################################

En versiones superiores se creará una tabla en la bbdd con la mayoría de modelos de coche donde se almacenarán datos de medidas de neumáticos, tipo de aceite que necesita y referencias de los consumibles que necesita en cada revisión así como las acciones a realizar según la cantidad de kilómetros o antigüedad del mismo. Toda esta información aparecerá en los detalles de cada tarea del mecánico y se realizará automáticamente el pedido de las piezas necesarias al proveedor vía email.

**Comment by chufaschufurius** [comment]
OK
